version: "3.8"

services:
  ps-psql:
    image: postgres:15-alpine
    container_name: ps-psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prodservice
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prodservice"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-production-service-app
    ports:
      - "30000:30000" # gRPC порт
      - "30001:30001" # HTTP порт
    environment:
      - CONFIG_PATH=/app/configs/config.local.yaml
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - app-network
    depends_on:
      ps-psql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
